[package]
name = "test-meta-package"
version = "0.1.0"
authors = ["aksenzhuk"]
edition = "2018"

[lib]
name = "test_component"
crate-type = ["cdylib"]

[dependencies]
config = "0.9"
package = { path = "../package", version = "0.1" }
entity = { path = "../entity", version = "0.1" }
