[package]
name = "depot"
version = "0.1.0"
authors = ["aksenzhuk"]
edition = "2018"

[dependencies]
log = "0.4"
libloading = "0.5"
config = "0.9"
serde = "1.0"
serde_derive = "1.0"
package = { path = "../package", version = "0.1" }
